import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFile } from "node:fs/promises";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// React DOM 19 contains three resource-hoisting branches that can dynamically
// create <script> elements. Momento never renders scripts or calls React's
// preinit/preload APIs, so exclude that capability from the shipped bundle.
// Keep the exact-match assertion: if React DOM changes, the release build must
// be reviewed instead of silently shipping a new dynamic script path.
const disableUnusedReactScriptInjection = {
	name: 'disable-unused-react-script-injection',
	setup(build) {
		build.onLoad(
			{ filter: /react-dom[\\/]cjs[\\/]react-dom-client\.production\.js$/ },
			async ({ path }) => {
				let contents = await readFile(path, 'utf8');
				let replacementCount = 0;

				contents = contents.replace(
					/\.createElement\("script"\)/g,
					() => {
						replacementCount += 1;
						return '.createElement("template")';
					},
				);

				if (replacementCount !== 3) {
					throw new Error(
						`Expected to disable 3 React DOM script creation paths, found ${replacementCount}.`,
					);
				}

				return { contents, loader: 'js' };
			},
		);
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	minify: prod,
	legalComments: 'none',
	sourcesContent: false,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	plugins: prod ? [disableUnusedReactScriptInjection] : [],
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
